---

all:
  vars:
    docker_env_path: "{{ playbook_dir }}/../zabbix-environment"
    web_direct: "http://localhost:8080"
    web_default: "http://localhost:80"
    web_basicauth: "http://localhost:81"
    basicauth_user: "Admin"
    basicauth_pass: "zabbix"
    zabbix_user: "Admin"
    zabbix_pass: "zabbix"
    #
    ansible_host: localhost
  children:
    with_zapi:
      vars:
        ansible_connection: local
        ansible_host: localhost
        connection_type: auto
      hosts:
        zapi_default:
          server_url: "{{ web_default }}"
        zapi_basicauth:
          server_url: "{{ web_basicauth }}"
        zapi_direct:
          server_url: "{{ web_direct }}"
    with_httpapi:
      vars:
        connection_type: httpapi
        ansible_user: Admin
        ansible_httpapi_pass: zabbix
        ansible_network_os: community.zabbix.jsonrpc
        ansible_connection: community.zabbix.httpapi
        ansible_host: host.docker.internal
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
      hosts:
        httpapi_default:
          ansible_httpapi_port: 80
        httpapi_direct:
          ansible_httpapi_port: 8080
        # httpapi_basicauth:
        #   ansible_httpapi_port: 81
        #   ansible_httpapi_basic_auth_user: Admin
        #   ansible_httpapi_basic_auth_password: zabbix

...